### ISSUE TITLE
Future of this project

### ISSUE THREAD

**Issue by asuender** [PocketBase4J/PocketBase4J#13]
You mentioned in #11 that you aren't working on this library right now but I've already made some commits in my own fork, therefore I can help you with this if you like.

**Comment by nothub** [comment]
Yeah sure you are welcome to do so :)
I can also give you permissions in this repo or we move it to an organisation or whatever works for you :+1:

**Comment by asuender** [comment]
We could move it to an organization as this would be a new experience for me as an IT student. I leave this choice to you 👍 .

**Comment by nothub** [comment]
Okay cool, I gonna create an orga, move the repo there and send you an invite.

**Comment by nothub** [comment]
Okay I created an orga [here](https://github.com/PocketBase4J). I sent you an invite with Owner permissions. Just change anything you seem necessary :ok_hand:. Do you use Discord?

**Comment by asuender** [comment]
Thank you very much! Yes, I use Discord.

**Comment by nothub** [comment]
I am `hub#6408` on discord, feel free to add me :)
